version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ef-learning-postgres
    environment:
      POSTGRES_DB: EntityFrameworkLearning
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - ef-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ef-learning-api
    ports:
      - "5000:8080"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=EntityFrameworkLearning;Username=postgres;Password=postgres
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - ef-network

volumes:
  postgres_data:

networks:
  ef-network:
    driver: bridge 